routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware'=>'auth'], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/totalWinner', 'WardController@totalWinner');
    Route::resource('people', 'PersonController');//resource route
    Route::resource('person', 'PersonController');//resource route
    Route::resource('win', 'WinController');//resource route
    Route::get('winpdf/{win_ids}', 'WinController@download');
    Route::resource('ward', 'WardController');
//    Route::post('ward', 'WardController@saveMaxWinner');

    Route::get('winners/{win}/download_excel', 'WinController@downloadExcel')->name('winners.download_excel');
    Route::get('winners/{win}/send_email', 'WinController@sendEmailToWinners')->name('winners.send_email');

});

app/Person.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Person extends Model
{
    protected $table = 'persons';
    protected $fillable = ['win_ids', 'is_win', 'win_date'];
    protected $dates = ['win_date'];

    public function ward()
    {
        return $this->belongsTo(Ward::class);
    }

    public function scopeIsNotWinner($query){
        return $query->where('is_win', 0);
    }

}

app/Http/Controllers/PersonController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Person;
use App\Win;
use App\Ward;
class PersonController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ('person.index') {
            $search = $request->get('search');
            $persons = Person::select('name','phone','gender','id');
            if (isset($search) && $search != null) {
                $persons = $persons->where('name', 'LIKE', "%{$search}%")
                    ->orwhere('phone', 'LIKE', "%{$search}%")
                    ->orWhere('gender', 'LIKE', "{$search}%");
            }
            $persons = $persons->latest()->paginate(100);
            $alldata = Person::all();
            $count = count($alldata);
            return view('person.index', compact('persons','count'));
        } else {// true
            return redirect('/');
        }
    }        /**
         * Show the form for creating a new resource.
         *
         * @return \Illuminate\Http\Response
         */
        public function create()
        {
            $wards = Ward::orderBy('title','asc')->pluck('title', 'id');
            return view('person.create',compact('wards'));
        }

        /**
         * Store a newly created resource in storage.
         *
         * @param  \Illuminate\Http\Request $request
         * @return \Illuminate\Http\Response
         */
        public function store(Request $request)
        {
//            $ward = explode(",",$ward->ward_name);

            $persons = new Person;
            $persons->unique_id = $request->unique_id;
            $persons->name = $request->name;
            $persons->gender = $request->gender;
            $persons->father_name = $request->father_name;
            $persons->mother_name = $request->mother_name;
            $persons->address = $request->address;
            $persons->address1 = $request->address1;
            $persons->address2 = $request->address2;
            $persons->category = $request->category;
            $persons->ref = $request->ref;
            $persons->area = $request->area;
            $persons->ward_id = $request->ward_id;
            $persons->phone = $request->phone;
            $persons->email = $request->email;
            $persons->nid = $request->nid;


            if ( $persons->save()) {
                return redirect()->back()->with('message_success', "Insert Successfully");
            } else {
                return redirect()->back()->with('message_error', "Sorry Please try again.");
            }
           // return view('person.index',compact('win','persons'));
         // $persons->ward()->sync($request->ward);
        }


    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

        $person= Person::find($id);
        return view('person.show')->with('person',$person);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $wards = Ward::orderBy('title','asc')->pluck('title', 'ward_name');
        $person = Person::where('id',$id)->first();
        return view('person.edit',compact('person','wards'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $persons = Person::find($id);
        // $lotteries->unique_id= $request->unique_id;
        $persons->name= $request->name;
        $persons->gender= $request->gender;
        $persons->father_name= $request->father_name;
        $persons->mother_name= $request->mother_name;
        $persons->address= $request->address;
        $persons->address1= $request->address1;
        $persons->address2= $request->address2;
        $persons->category = $request->category;
        $persons->ref = $request->ref;
        $persons->area= $request->area;
        $persons->ward_name = $request->ward_name;
        $persons->phone= $request->phone;
        $persons->email = $request->email;
        $persons->nid= $request->nid;
        $persons->is_win = $request->is_win;//this field will be 0 for every insert...no need any in field in form
//        $persons->date= $request->date;// no need to store this field remove it from form default will be null..these tow fields
                                        //will update only when win the lotery..

        $persons->save() ;
      //  $persons->ward()->sync($request->ward_name);
        return redirect(route('person.index'))->withMessage(' Updated Successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Person::destroy($id);
        return redirect()->back()->withMessage('Deleted Successfully');
    }
}

resources/views/person/create.blade.php
@extends('layouts.master')

@section('content')

<div class="panel panel-success">

    <div class="panel-heading">
        <h2>Person Create Form</h2>
    </div>

    <div class="panel-body " >
        <form class="form-horizontal" method="POST" action="{{ route('person.store') }}">
            {{ csrf_field() }}

            <div class="form-group">
                {{--<label for="unique_id" class="col-md-4 control-label">unique_id</label>--}}

                <div class="col-md-6 ">
                    <input id="unique_id" type="hidden" class="form-control " name="unique_id" value="{{ rand(1000,11000) }}">
                </div>
            </div>
            <div class="form-group">
                <label for="name" class="col-md-2 control-label">Name</label>

                <div class="col-md-6">
                    <input id="name" type="text" class="form-control " name="name" >
                </div>
            </div>


            <div class="form-group">
                <label for="father_name" class="col-md-2 control-label">Father Name</label>

                <div class="col-md-6">
                    <input id="father_name" type="text" class="form-control " name="father_name" >
                </div>
            </div>
            <div class="form-group">
                <label for="mother_name" class="col-md-2 control-label">Mother Name</label>

                <div class="col-md-6">
                    <input id="mother_name" type="text" class="form-control" name="mother_name" >
                </div>
            </div>
            <div class="form-group">
                <label for="address" class="col-md-2 control-label">Address</label>

                <div class="col-md-6">
                    <textarea id="address" type="text" class="form-control " name="address" ></textarea>
                </div>
            </div>
            <div class="form-group">
                <label for="address1" class="col-md-2 control-label">Address 1</label>

                <div class="col-md-6">
                    <input id="address1" type="text" class="form-control " name="address1" >
                </div>
            </div>
            <div class="form-group">
                <label for="address2" class="col-md-2 control-label">Address 2</label>

                <div class="col-md-6">
                    <input id="address2" type="text" class="form-control " name="address2" >
                </div>
            </div>
            <div class="form-group">
                <label for="category" class="col-md-2 control-label">Category</label>

                <div class="col-md-6">
                    <input id="category" type="text" class="form-control " name="category" >
                </div>
            </div>
            <div class="form-group">
                <label for="ref" class="col-md-2 control-label">Reference</label>

                <div class="col-md-6">
                    <input id="ref" type="text" class="form-control " name="ref" >
                </div>
            </div>
            <div class="form-group">
                <label for="area" class="col-md-2 control-label">Area</label>

                <div class="col-md-6">
                    <input id="area" type="text" class="form-control" name="area" >
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 control-label"> Ward</label>
                <div class="col-md-6">
                <select class="form-control" name="ward_id"  >
                    <option >Select Ward</option>
                    @foreach($wards as $key=>$value)
                        <option  value="{{ $key }}">{{ $value}}</option>
                    @endforeach
                </select>

                </div>
            </div>

            <div class="form-group">
                <label for="phone" class="col-md-2 control-label">Phone</label>

                <div class="col-md-6">
                    <input id="phone" type="number" class="form-control " name="phone" >
                </div>
            </div>
            <div class="form-group">
                <label for="email" class="col-md-2 control-label">E-mail</label>

                <div class="col-md-6">
                    <input id="email" type="text" class="form-control " name="email" >
                </div>
            </div>
            <div class="form-group">
                <label for="nid" class="col-md-2 control-label">NID</label>

                <div class="col-md-6">
                    <input id="nid" type="number" class="form-control " name="nid" >
                </div>
            </div>

            <div class="form-group">
                <label for="is_win" class="col-md-2 control-label">Win</label>

                <div class="col-md-6">
                    <input id="is_win" type="text" class="form-control " name="is_win" >
                </div>
            </div>

            <div class="form-group">
                <label for="gender" class="col-md-2 control-label">Gender </label>


                <div class=" col-md-8">
                            <div class="form-check" >
                                <input class="form-check-input" type="radio" name="gender" id="male" value="male" checked>
                                <label class="form-check-label" for="male">
                                    <p>Male</p>
                                </label>
                            </div>

                            <div class="form-check ">
                                <input class="form-check-input" type="radio" name="gender" id="female" value="female">
                                <label class="form-check-label" for="female">
                                    <p>Female</p>
                                </label>
                            </div>

                </div>

            </div>
            <div class="form-group">
                <div class="col-md-6 col-md-offset-4">

                    <button type="submit" class="btn btn-primary">Submit</button>
                    <a href="{{ route('person.index') }}" class=" btn btn-primary">Person</a>
                </div>
            </div>
        </form>
    </div>

</div>

@endsection

resources/views/person/edit.blade.php
@extends('layouts.master')

@section('content')

                <div class="panel panel-success">
                <div class="panel-heading"><h2 >Person Edit Form</h2></div>

                <div class="panel-body " >
                    <form class="form-horizontal" method="POST" action="{{ route('person.update',$person->id) }}">
                        {{ csrf_field() }}
                        {{ method_field('PATCH') }}

                        {{--<div class="form-group">--}}
                            {{--<label for="unique_id" class="col-md-4 control-label">unique_id</label>--}}

                            {{--<div class="col-md-6">--}}
                                {{--<input id="unique_id" type="hidden" class="form-control colorize-theme6-bg" name="unique_id" value="{{ rand(1000,11000) }}">--}}
                            {{--</div>--}}
                        {{--</div>--}}
                        <div class="form-group">
                            <label for="name" class="col-md-2 control-label">Name</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control colorize-theme6-bg" name="name" value="{{ $person->name }}" >
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="father_name" class="col-md-2 control-label">Father_name</label>

                            <div class="col-md-6">
                                <input id="father_name" type="text" class="form-control colorize-theme6-bg" name="father_name" value="{{$person->father_name }}">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="mother_name" class="col-md-2 control-label">Mother_name</label>

                            <div class="col-md-6">
                                <input id="mother_name" type="text" class="form-control colorize-theme6-bg" name="mother_name" value="{{ $person->mother_name }}">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="address" class="col-md-2 control-label">Address</label>

                            <div class="col-md-6">
                                <input id="address" type="text" class="form-control colorize-theme6-bg" name="address" value="{{ $person->address}}">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="address1" class="col-md-2 control-label">Address 1</label>

                            <div class="col-md-6">
                                <input id="address1" type="text" class="form-control colorize-theme6-bg" name="address1" value="{{ $person->address1}}" >
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="address2" class="col-md-2 control-label">Address 2</label>

                            <div class="col-md-6">
                                <input id="address2" type="text" class="form-control colorize-theme6-bg" name="address2"value="{{ $person->address2}}" >
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="area" class="col-md-2 control-label">Area</label>

                            <div class="col-md-6">
                                <input id="area" type="text" class="form-control colorize-theme6-bg" name="area" value="{{ $person->area}}">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-md-2 control-label"> Ward</label>
                            <div class="col-md-6">
                                <select class="form-control" name="ward_name" >
                                    <option >Select Ward</option>
                                    @foreach($wards as $key=>$value)
                                        <option {{ $person->ward_name==$key? 'selected':''}} value="{{ $key }}">


                                            {{ $value}}
                                        </option>
                                    @endforeach
                                </select>

                            </div>
                        </div>
                        <div class="form-group">
                            <label for="phone" class="col-md-2 control-label">Phone</label>

                            <div class="col-md-6">
                                <input id="phone" type="number" class="form-control colorize-theme6-bg" name="phone" value="{{ $person->phone}}">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="nid" class="col-md-2 control-label">NID</label>

                            <div class="col-md-6">
                                <input id="nid" type="number" class="form-control colorize-theme6-bg" name="nid" value="{{ $person->nid}}" >
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="is_win" class="col-md-2 control-label">Win</label>

                            <div class="col-md-6">
                                <input id="is_win" type="text" class="form-control colorize-theme6-bg" name="is_win"  value="{{ $person->is_win}}" >
                            </div>
                        </div>
                        {{--<div class="form-group">--}}
                            {{--<label for="is_date" class="col-md-2 control-label">Date</label>--}}

                            {{--<div class="col-md-6">--}}
                                {{--<input id="is_date" type="date" class="form-control colorize-theme6-bg" name="is_date"  value="{{ $person->date}}" >--}}
                            {{--</div>--}}
                        {{--</div>--}}
                        <div class="form-group">
                            <label for="gender" class="col-md-2 control-label">Gender:</label>


                            <div class="form-group col-md-6">
                                <div class="form-check" >
                                    <input class="form-check-input" type="radio" name="gender" id="male" value="male"  value="{{ $person->gender}}" checked>
                                    <label class="form-check-label" for="male">
                                        <p>Male</p>
                                    </label>
                                </div>
                                <div class="form-check ">
                                    <input class="form-check-input" type="radio" name="gender" id="female" value="female" value="{{ $person->gender}}">
                                    <label class="form-check-label" for="female">
                                        <p>Female</p>
                                    </label>
                                </div>

                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">

                                <button type="submit" class="btn btn-primary">Submit</button>
                                <a href="{{ route('person.index') }}" class=" btn btn-primary">Person</a>
                                <a href="{{ route('person.create') }}" class=" btn btn-primary"> <span class=" glyphicon glyphicon-plus-sign"></span>Create</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>


@endsection

resources/views/person/index.blade.php
@extends('layouts.master')

@section('content')

                <div class="panel panel-success">
    <div class="panel-heading">
        <h2 >
            Persons List
            <a href="{{ route('person.create') }}" class=" btn btn-primary pull-right"> <span class=" glyphicon glyphicon-plus-sign"></span>Add  Person </a>

        </h2>
        <form class="form-inline" action="{{ route('person.index') }}" method="get">
            <input type="search" class="form-control colorize-theme6-bg" id="search"
                   placeholder="Search . . . ." name="search"
                   value="{{ (isset($_GET['search']) && !empty($_GET['search']))?$_GET['search']:"" }}">
            <button type="submit" class="btn btn-primary">Search</button>
        </form>
        We Have Total {{$count}}  Entries

         {{--<p>List of Previous Lotteries {{ $person->created_at}}</p>--}}

        {{--<div style="background:#00b38f; color: #ffffff; width: 600px;text-align: center; font-size: 20px;">{{ session('message') }}</div>--}}
    </div>
                    <div class="panel-body">
    <table id="example1" class="table table-responsive table table-bordered table-striped" style="text-align:center">
        <thead >
        <tr class="bg-primary" >
            <th style="text-align: center; ">SL#</th>
            {{--<th style="text-align:center">Unique Id</th>//don't show unique id here--}}
            <th style="text-align:center">Name</th>
            <th style="text-align:center">Phone</th>
            <th style="text-align:center">Gender</th>
            <th style="text-align:center">Action</th>

        </tr>
        </thead>
        <tbody>


        @foreach( $persons as $person )


            <tr>
                <td>{{ $loop->index + 1}}</td>
                <td>{{ $person->name }}</td>
                <td>{{ $person->phone}}</td>
                <td>{{ $person->gender}}</td>
                <td> <a href="{{ route('person.show',$person->id) }}" class=" btn btn-info" title="View"><span class=" glyphicon glyphicon-eye-open"></span></a>
                 {{--<a href="{{ route('lottery.view') }}" class=" btn btn-info"><span class=" glyphicon glyphicon-eye-open"></span></a>--}}

                    <a href="{{ route('person.edit',$person->id) }}" class=" btn btn-primary" title="Edit"><span class="glyphicon glyphicon-edit"></span></a>
                    <form id="delete-form-{{ $person->id }}" method="POST" action="{{ route('person.destroy',$person->id) }}" style="display: none">
                        {{ csrf_field() }}
                        {{ method_field('DELETE') }}
                    </form>
                    <a href="" onclick="
                            if(confirm('Are you sure, You went to delete this?'))

                            {
                            event.preventDefault();
                            document.getElementById('delete-form-{{ $person->id }}').submit();
                            }
                            else{
                            event.preventDefault();
                            }
                            " class=" btn btn-danger" title="Delete"><span class="glyphicon glyphicon-trash"></span></a>

                </td>
            </tr>
        @endforeach


        </tbody>

    </table>
       </div>
    {{ $persons->links() }}
          </div>
      </div>
   </div>
</div>
@endsection

resources/views/person/show.blade.php
@extends('layouts.master')

@section('content')

                <div class="panel panel-success">

                    <div class="panel-heading ">
                        <h2 >Person Information
                            <a href="{{ route('person.create') }}" class=" btn btn-primary pull-right"> <span class=" glyphicon glyphicon-plus-sign"></span>Create</a>
                            <a href="{{ route('person.index') }}" class=" btn btn-primary pull-right">Run Person</a>
                        </h2>

                    </div>
                    <div class="panel-body">
                    <table style="text-align: center" id="example1" class="table table-bordered table-striped">
                        <thead >
                        <tr class="bg-primary">
                            <th style="text-align: center;font-size: 20px">Title</th>
                            <th style="text-align: center;font-size: 20px">Information</th>


                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>Unique Id</td>
                            <td>{{ $person->unique_id }}</td>
                        </tr>
                            <tr>
                                <td>Name</td>
                                <td>{{ $person->name }}</td>
                            </tr>
                             <tr>
                                <td>Father Name</td>
                                <td>{{$person->father_name}}</td>
                            </tr>
                            <tr>
                                <td>Mother Name</td>
                                <td>{{$person->mother_name}}</td>
                            </tr>
                             <tr>
                                <td>Address</td>
                                <td>{{$person->address}}</td>
                            </tr>
                            <tr>
                                <td>Address1</td>
                                <td>{{$person->address1}}</td>
                            </tr>
                             <tr>
                                <td>Address2</td>
                                <td>{{$person->address2}}</td>
                            </tr>
                            <tr>
                                <td>Category</td>
                                <td>{{$person->category}}</td>
                            </tr>
                            <tr>
                                <td>Reference</td>
                                <td>{{$person->ref}}</td>
                            </tr>
                            <tr>
                                <td>Area</td>
                                <td>{{$person->area}}</td>
                            </tr>
                          <tr>

                                <td>Ward Name</td>
                                <td>{{$person->ward_name}}</td>
                            </tr>
                           <tr>
                                <td>Phone</td>
                                <td>{{$person->phone}}</td>
                            </tr>
                           <tr>
                                <td>E-mail</td>
                                <td>{{$person->email}}</td>
                            </tr>

                           <tr>
                                <td>NID</td>
                                <td>{{$person->nid}}</td>
                            </tr>
                          <tr>
                                <td>Win</td>
                                <td>{{$person->is_win}}</td>
                            </tr>




                            <tr>
                                <td>Gender</td>
                                <td>{{$person->gender}}</td>
                            </tr>


                        </tbody>

                    </table>

      </div>








                  </div>

@endsection