routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware'=>'auth'], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/totalWinner', 'WardController@totalWinner');
    Route::resource('people', 'PersonController');//resource route
    Route::resource('person', 'PersonController');//resource route
    Route::resource('win', 'WinController');//resource route
    Route::get('winpdf/{win_ids}', 'WinController@download');
    Route::resource('ward', 'WardController');
//    Route::post('ward', 'WardController@saveMaxWinner');

    Route::get('winners/{win}/download_excel', 'WinController@downloadExcel')->name('winners.download_excel');
    Route::get('winners/{win}/send_email', 'WinController@sendEmailToWinners')->name('winners.send_email');

});

app/Ward.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Ward extends Model
{

}

app/Http/Controllers/WardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Ward;
class WardController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $wards = Ward::latest()->paginate(5);
        return view('ward.index',compact('wards'));

    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('ward.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $ward = new Ward;
        $ward->title = $request->title;
        $ward->ward_name = $request->ward_name;
        $ward->save();


        return redirect(route('ward.index'))->withMessage('ward Added');
    }


    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $ward = Ward::find($id);
        return view('ward.show')->with('ward',$ward);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $ward = Ward::where('id',$id)->first();
        return view('ward.edit',compact('ward'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $ward = Ward::find($id);
       $ward->title = $request->title;
      $ward->ward_name= $request->ward_name;
        $ward->percent= $request->percent;
        $ward->save();

        return redirect(route('ward.index'))->withMessage('Wards Is Updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Ward::where('id',$id)->delete();
        return redirect()->back()->withMessage('Ward Is Deleted');
    }


    public function totalWinner()
    {
        $wards = Ward::all();
        return view('ward.totalWinner',compact('wards'));

    }

    public function saveMaxWinner(Request $r)
    {
        dd($r);

    }
}

resources/views/ward/create.blade.php
@extends('layouts.master')

@section('content')

    <div class="panel panel-success">

        <div class="panel-heading">
            <h2>Ward Create Form</h2>
        </div>

        <div class="panel-body " >
            <form class="form-horizontal" method="POST" action="{{ route('ward.store') }}" enctype="multipart/form-data">
                {{ csrf_field() }}


                <div class="form-group">
                    <label for="title" class="col-md-2 control-label">Title</label>

                    <div class="col-md-6">
                        <input id="title" type="text" class="form-control " name="title" >
                    </div>
                </div>

                <div class="form-group">
                    <label for="ward_name" class="col-md-2 control-label">Ward Name</label>

                    <div class="col-md-6">
                        <input id="ward_name" type="text" class="form-control " name="ward_name" >
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-6 col-md-offset-4">

                        <button type="submit" class="btn btn-primary">Submit</button>
                        <a href="{{ route('ward.index') }}" class=" btn btn-primary">Ward</a>
                    </div>
                </div>
            </form>
        </div>

    </div>

@endsection

resources/views/ward/edit.blade.php
@extends('layouts.master')

@section('content')

                <div class="panel panel-success">
                <div class="panel-heading"><h2 >Ward Edit Form</h2></div>

                <div class="panel-body " >
                    <form class="form-horizontal" method="POST" action="{{ route('ward.update',$ward->id) }}">
                        {{ csrf_field() }}
                        {{ method_field('PATCH') }}


                        <div class="form-group">
                            <label for="title" class="col-md-2 control-label">Title</label>

                            <div class="col-md-6">
                                <input id="title" type="text" class="form-control " name="title" value="{{ $ward->title }}">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="ward_name" class="col-md-2 control-label">Ward Name</label>

                            <div class="col-md-6">
                                <input id="ward_name" type="text" class="form-control " name="ward_name" value="{{ $ward->ward_name }}" >
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">

                                <button type="submit" class="btn btn-primary">Submit</button>
                                <a href="{{ route('ward.index') }}" class=" btn btn-primary">ward</a>
                                <a href="{{ route('ward.create') }}" class=" btn btn-primary"> <span class=" glyphicon glyphicon-plus-sign"></span>Create</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>


@endsection

resources/views/ward/index.blade.php
@extends('layouts.master')

@section('content')

                <div class="panel panel-success">
    <div class="panel-heading">
        <h2 >
            Wards List
            <a href="{{ route('ward.create') }}" class=" btn btn-primary pull-right"> <span class=" glyphicon glyphicon-plus-sign"></span>Add  ward </a>

        </h2>



         {{--<p>List of Previous Lotteries {{ $ward->created_at}}</p>--}}

        {{--<div style="background:#00b38f; color: #ffffff; width: 600px;text-align: center; font-size: 20px;">{{ session('message') }}</div>--}}
    </div>
                    <div class="panel-body">
    <table id="example1" class="table table-responsive table table-bordered table-striped" style="text-align:center">
        <thead >
        <tr class="bg-primary" >
            <th style="text-align: center; ">SL#</th>
            {{--<th style="text-align:center">Unique Id</th>//don't show unique id here--}}
            <th style="text-align:center">Title</th>
            <th style="text-align:center">Ward</th>
            <th style="text-align:center">Action</th>

        </tr>
        </thead>
        <tbody>


        @foreach( $wards as $ward )


            <tr>
                <td>{{ $loop->index + 1}}</td>
                <td>{{ $ward->title }}</td>
                <td>{{ $ward->ward_name}}</td>
                <td> <a href="{{ route('ward.show',$ward->id) }}" class=" btn btn-info" title="View"><span class=" glyphicon glyphicon-eye-open"></span></a>
                 {{--<a href="{{ route('lottery.view') }}" class=" btn btn-info"><span class=" glyphicon glyphicon-eye-open"></span></a>--}}

                    <a href="{{ route('ward.edit',$ward->id) }}" class=" btn btn-primary" title="Edit"><span class="glyphicon glyphicon-edit"></span></a>
                    <form id="delete-form-{{ $ward->id }}" method="POST" action="{{ route('ward.destroy',$ward->id) }}" style="display: none">
                        {{ csrf_field() }}
                        {{ method_field('DELETE') }}
                    </form>
                    <a href="" onclick="
                            if(confirm('Are you sure, You went to delete this?'))

                            {
                            event.preventDefault();
                            document.getElementById('delete-form-{{ $ward->id }}').submit();
                            }
                            else{
                            event.preventDefault();
                            }
                            " class=" btn btn-danger" title="Delete"><span class="glyphicon glyphicon-trash"></span></a>

                </td>
            </tr>
        @endforeach


        </tbody>

    </table>
       </div>
    {{ $wards->links() }}
          </div>
      </div>
   </div>
</div>
@endsection

resources/views/ward/show.blade.php
@extends('layouts.master')

@section('content')

                <div class="panel panel-success">

                    <div class="panel-heading ">
                        <h2 >Ward Information
                            <a href="{{ route('ward.create') }}" class=" btn btn-primary pull-right"> <span class=" glyphicon glyphicon-plus-sign"></span>Create</a>
                            <a href="{{ route('ward.index') }}" class=" btn btn-primary pull-right">Run Ward</a>
                        </h2>

                    </div>
                    <div class="panel-body">
                    <table style="text-align: center" id="example1" class="table table-bordered table-striped">
                        <thead >
                        <tr class="bg-primary">
                            <th style="text-align: center;font-size: 20px">Title</th>
                            <th style="text-align: center;font-size: 20px">Ward</th>


                        </tr>
                        </thead>
                        <tbody>
                        <tr>

                            <td>{{ $ward->title }}</td>
                            <td>{{ $ward->ward_name }}</td>
                        </tr>


                        </tbody>

                    </table>

                   </div>








                  </div>

@endsection

resources/views/ward/totalWinner.blade.php
@extends('layouts.master')

@section('content')

    <div class="panel panel-success">
        <div class="panel-heading">
            <h2 style="text-align: center">Total Ward</h2>
        </div>

        <div class="panel-body">
            <form class="form-horizontal" method="POST" action="{{ route('ward.saveMaxWinner')}}">
                {{ csrf_field() }}
                {{ method_field('PATCH') }}

                <div class="form-group">
                <label for="ward_name" class="col-md-4 control-label">Ward Name</label><br/>


                <div class="col-md-8">

                    @foreach ($wards as $ward)

                        <label class="form-check-label">
                            <table>
                                <tr >
                                 <td>{{ $ward->ward_name }}-{{ $ward->id }}:- </td>
                                <td > <input type="number" name="ward_{{$ward->id}}" value="0"> </td>
                                </tr>
                            {{--{{ $ward->ward_name }}-{{ $ward->id }}:-  <input type="number" name="wards[]" value="1">  <br/><br/>--}}
                                </table>
                        </label>

                    @endforeach


                </div>
                </div>


                <div class="form-group text-center">
                    <button type="submit" class="btn btn-primary">Save</button>

                </div>
            </form>
        </div>
    </div>

@endsection