routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware'=>'auth'], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/totalWinner', 'WardController@totalWinner');
    Route::resource('people', 'PersonController');//resource route
    Route::resource('person', 'PersonController');//resource route
    Route::resource('win', 'WinController');//resource route
    Route::get('winpdf/{win_ids}', 'WinController@download');
    Route::resource('ward', 'WardController');
//    Route::post('ward', 'WardController@saveMaxWinner');

    Route::get('winners/{win}/download_excel', 'WinController@downloadExcel')->name('winners.download_excel');
    Route::get('winners/{win}/send_email', 'WinController@sendEmailToWinners')->name('winners.send_email');

});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->

    {{--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">--}}
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">



</head>
<body>
    <div id="app">
        @include('layouts.nav')


        @yield('content')
    </div>




    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>

    {{--@stack('scripts')--}}
</body>

</html>

resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
<div id="app">
    @include('layouts.nav')

    <div class="container">
        <div class="row">
            <div class="col-md-12">
             @yield('content')
            </div>
        </div>
    </div>
</div>

<!-- Scripts -->
<script src="{{ asset('js/app.js') }}"></script>

@stack('scripts')
</body>

</html>

resources/views/layouts/nav.blade.php
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">

            <!-- Collapsed Hamburger -->
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse" aria-expanded="false">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <!-- Branding Image -->
            {{--<a class="navbar-brand" href="{{ url('/') }}">--}}
            {{--{{ config('app.name', 'Laravel') }}--}}
            {{--</a>--}}
            {{--<a href="{{ route('home') }}">--}}
            {{--<img src="{{ asset('images/icc.png') }}" alt="CCCL">--}}
            {{--</a>--}}
            <ul class="nav navbar-nav navbar-reft">
                @auth
                <li><a href="{{ route('person.index') }}" class="bg-{{ (request()->segment(1) == 'person' ? 'danger' : 'info') }}"><b>Person</b></a></li>
                <li><a href="{{ route('win.index') }}"  class="bg-{{ (request()->segment(1) == 'win' ? 'danger' : 'info') }}"><b>Win</b></a></li>
                <li><a href="{{ route('ward.index') }}"  class="bg-{{ (request()->segment(1) == 'ward' ? 'danger' : 'info') }}"><b>Ward</b></a></li>
                {{--                    <li><a href="{{ route('ward.create') }}"><b>Random Selection</b></a></li>--}}
                @endauth
            </ul>
        </div>

        <div class="collapse navbar-collapse" id="app-navbar-collapse">
            <!-- Left Side Of Navbar -->
            <ul class="nav navbar-nav">
                &nbsp;
            </ul>

            <!-- Right Side Of Navbar -->
            <ul class="nav navbar-nav navbar-right">
                <!-- Authentication Links -->
                @guest
                <li><a href="{{ route('login') }}"><b>Login</b></a></li>
                <li><a href="{{ route('register') }}"><b>Register</b></a></li>
                @else
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true" v-pre>
                            {{ Auth::user()->name }} <span class="caret"></span>
                        </a>

                        <ul class="dropdown-menu">
                            <li>
                                <a href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    Logout
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    {{ csrf_field() }}
                                </form>
                            </li>
                        </ul>
                    </li>
                    @endguest
            </ul>
        </div>
    </div>
</nav>