routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware'=>'auth'], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/totalWinner', 'WardController@totalWinner');
    Route::resource('people', 'PersonController');//resource route
    Route::resource('person', 'PersonController');//resource route
    Route::resource('win', 'WinController');//resource route
    Route::get('winpdf/{win_ids}', 'WinController@download');
    Route::resource('ward', 'WardController');
//    Route::post('ward', 'WardController@saveMaxWinner');

    Route::get('winners/{win}/download_excel', 'WinController@downloadExcel')->name('winners.download_excel');
    Route::get('winners/{win}/send_email', 'WinController@sendEmailToWinners')->name('winners.send_email');

});

app/Win.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Win extends Model
{
//    public function win()
//    {
//        return $this->hasOne('App\Person');
//    }
}

app/Http/Controllers/WinController.php
<?php

namespace App\Http\Controllers;

use App\Mail\Winner;
use App\Ward;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Win;
use App\Person;
use Barryvdh\DomPDF\Facade as PDF;
use Maatwebsite\Excel\Facades\Excel;
use Illuminate\Database\QueryException as Exception;


class WinController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

//        if ('win.index') {
//            $search = $request->get('search');
//            $wins = Win::select('title');
//            if (isset($search) && $search != null) {// you should refactor this code
//                $wins = $wins->where('title', 'LIKE', "%{$search}%");
//            }
//            $wins = $wins->latest()->paginate(20);
//            $alldata = Win::all();
//            $count = count($alldata);
//            return view('win.index', compact('wins','count'));
//        } else {// true
//            return redirect('/');
//        }
        $wins = Win::latest()->paginate(10);
        return view('win.index',compact('wins'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $win_ids = Person::where('is_win',0)->pluck('id');
        $wards = Ward::orderBy('ward_name','asc')->pluck('ward_name','id');
        return view('win.create', compact('win_ids','wards'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $i = 0;
        $wins = [];
       if($request->differ_in_gender == 'yes'){
           foreach ($request->ward_ids as  $ward_id){

               $ward = Ward::findOrFail($ward_id);

               $numberOfMail = Person::IsNotWinner()
                   ->where('gender','male')
                   ->where('ward_id', $ward_id)
                   ->pluck('id')
                   ->count();

               $numberOfFemale = Person::IsNotWinner()
                   ->where('gender','female')
                   ->where('ward_id', $ward_id)
                   ->pluck('id')
                   ->count();

               if($numberOfMail < $request->winners_per_word[$i]/2){
                   return redirect()->back()->withInput()->withErrors('There are '.$numberOfMail.' male persons available at '.$ward->ward_name. ' ward. Please check input for the ward..');
               }

               if($numberOfFemale < $request->winners_per_word[$i]/2){
                   return redirect()->back()->withInput()->withErrors('There are '.$numberOfFemale.' female persons available at '.$ward->ward_name. ' ward. Please check input for the ward..');
               }

               $male = Person::IsNotWinner()
                            ->where('gender','male')
                            ->where('ward_id', $ward_id)
                            ->pluck('id')
                            ->random($request->winners_per_word[$i]/2)
                            ->toArray();
               $female = Person::IsNotWinner()
                            ->where('gender','female')
                           ->where('ward_id', $ward_id)
                           ->pluck('id')
                           ->random($request->winners_per_word[$i]/2)
                           ->toArray();

               $winners = array_merge($male, $female);
               $winIds = array_merge($winners, $wins);
               $wins = $winIds;

               $i++;
           }
        }else{
           foreach ($request->ward_ids as  $ward_id){

               $ward = Ward::findOrFail($ward_id);

               $numberOfPerson = Person::IsNotWinner()
                   ->where('ward_id', $ward_id)
                   ->pluck('id')
                   ->count();

               if($numberOfPerson < $request->winners_per_word[$i]/2){
                   return redirect()->back()->withInput()->withErrors('There are '.$numberOfPerson.' male persons available at '.$ward->ward_name. ' ward. Please check input for the ward..');
               }

               $winners = Person::IsNotWinner()
                                ->where('ward_id', $ward_id)
                                ->pluck('id')
                                ->random($request->winners_per_word[$i])->toArray();
               $winIds = array_merge($winners, $wins);
               $wins = $winIds;
               $i++;
           }
        }

        foreach ($winIds as $id){
            $person = Person::findOrFail($id);
            $person->update(['is_win' => 1, 'win_date' => Carbon::now()->toDateTimeString()]);
        }

        $wins = new Win();
        $wins->title = $request->title;
        $wins->number_of_winners = array_sum($request->winners_per_word);
        $wins->win_ids = json_encode($winIds);
        //$wins->win_ids= $request->win_ids;
        $wins->save() ;

        return redirect(route('win.index'))->withMessage('Added Successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Win $win)
    {
        $winners = json_decode($win->win_ids);
        //$winners = explode(",",$win->win_ids);
        $persons = Person::whereIn('id',$winners)->get();
        //$wards = Ward::whereIn('id','ward_name')->get();
        return view('win.show', compact('persons', 'win'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $win= Win::where('id',$id)->first();
        return view('win.edit',compact('win'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $wins = Win::find($id);
        $wins->title = $request->title;
        $wins->win_ids= $request->win_ids;
        $wins->save() ;

        return redirect(route('win.index'))->withMessage('Updated Successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Win::where('id',$id)->delete();
        return redirect()->back()->withMessage(' Deleted Successfully');
    }

    public function download($win_ids)
    {
        $win = Win::find($win_ids);
        $winners = explode(",",$win->win_ids);
        $persons = Person::whereIn('id',$winners)->get();
        $pdf = PDF::loadView('win.download',compact('persons'));
        return $pdf->download('win.pdf');
    }

    public function downloadExcel(Win $win)
    {
        $winners = json_decode($win->win_ids);
        $winners = Person::whereIn('id',$winners)->get(['name', 'gender', 'phone', 'email', 'address', 'ward_name']);
        return Excel::create('winners.',function($excel) use ($winners){
            $excel->sheet('mySheet',function($sheet) use ($winners){
                $sheet->fromArray($winners);
            });
        })->download("xlsx");
    }

    public function sendEmailToWinners(Win $win)
    {
        $winners = json_decode($win->win_ids);
        Person::whereIn('id',$winners)->get()->each(function($winner) use ($winners){
            try{
                \Mail::to($winner)->send(new Winner($winner));
            }catch (Exception $e){
                \Log::info($e->getMessage());
            }
        });
        return redirect()->back()->withMessage('Emails has been sent to the winners');

    }
}

resources/views/win/create.blade.php
@extends('layouts.master')

@section('content')

<div class="panel panel-success">
    <div class="panel-heading">
        <h2 style="text-align: center">Win Lottery Form</h2>
        <ul class="bg-warning text-white">
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>

    <div class="panel-body">
        <form class="form-horizontal" method="POST" action="{{ route('win.store') }}" enctype="multipart/form-data">
            {{ csrf_field() }}

            <div class="form-group">
                <label for="title" class="col-md-3 control-label">Title</label>
                <div class="col-md-6">
                    <input id="title" type="text" class="form-control" name="title" value="{{ old('title') }}">
                </div>
            </div>

            {{--<div class="form-group">--}}
                {{--<label for="number_Of_winners" class="col-md-3 control-label">Number Of Winners</label>--}}
                {{--<div class="col-md-6">--}}
                    {{--<input id="number_Of_winners" type="number" class="form-control" name="number_Of_winners" >--}}
                {{--</div>--}}
            {{--</div>--}}

            <div class="form-group">
                <label for="ward_name" class="col-md-3 control-label">Distribution Of Winners</label>
                <div class="col-md-6">
                    <table class="table">
                        <thead>
                            <th>Ward</th>
                            <th>Number Of Winners</th>
                        </thead>
                        <tbody>
                            @foreach ($wards as $key => $value)
                                <tr>
                                    <td><input type="hidden" name="ward_ids[]" value="{{ $key }}"> {{ $value }}</td>
                                    <td><input type="number" name="winners_per_word[]" placeholder="Number Of Winners" value="0"></td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>

            <div class="form-group">
                <label for="differ_in_gender" class="col-md-3 control-label">Difference In Gender ? </label>

                <div class="col-md-6">

                        <label class="form-check-label">
                            <input type="checkbox" name="differ_in_gender" value="yes">

                        </label>


                </div>
            </div>


            {{--<div class="form-group">--}}
                {{--<label for="win_id" class="col-md-3 control-label">WinIds</label>--}}

                {{--<div class="col-md-6">--}}
                    {{--<textarea id="win_id" type="text" class="form-control" name="win_ids" readonly="readonly"></textarea>--}}
                {{--</div>--}}
            {{--</div>--}}

            <div class="form-group text-center">

                    {{--<button type="button" onclick="getWinners()" class=" btn btn-warning">Get Winner</button>--}}
                    <button type="submit" class="btn btn-primary">Save</button>

            </div>
        </form>
    </div>
</div>

@endsection

{{--@push('scripts')--}}

{{--<script>--}}

      {{--function shuffle(array) {--}}
          {{--var currentIndex = array.length, temporaryValue, randomIndex;--}}
          {{--// While there remain elements to shuffle...--}}
          {{--while (0 !== currentIndex) {--}}
              {{--// Pick a remaining element...--}}
              {{--randomIndex = Math.floor(Math.random() * currentIndex);--}}
              {{--currentIndex -= 1;--}}
              {{--// And swap it with the current element.--}}
              {{--temporaryValue = array[currentIndex];--}}
              {{--array[currentIndex] = array[randomIndex];--}}
              {{--array[randomIndex] = temporaryValue;--}}
          {{--}--}}
          {{--return array;--}}
      {{--}--}}

      {{--function getWinners(){--}}
          {{--var winIds = shuffle({{$win_ids}}).slice(0,100);--}}
          {{--$('#win_id').val(winIds);--}}
      {{--}--}}




{{--</script>--}}


{{--@endpush--}}

resources/views/win/download.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<div class="panel panel-success">

    <div class="panel-heading ">
        <h1 style="text-align: center;color: blue">
            Winners of Lottery
        </h1>

    </div>

    <div class="panel-body">
        {{--<h2 class="text-center">{{ $win->title}}</h2>--}}

        <table class="table table-bordered table-striped"  style="width:100%">

            <thead style="border: 1px solid black;text-align: center">

            <tr class="bg-info">
                <th>Name</th>
                <th>Phone</th>
                <th>Address</th>
            </tr>
            </thead>
            {{--{{ $win->win_ids }}--}}
            <tbody >


            @foreach( $persons as $person )

                <tr>

                    <td>{{ $person->name}}</td>
                    <td>{{ $person->phone}}</td>
                    <td>{{ $person->address }}</td>

                </tr>
            @endforeach

            </tbody>
        </table>
    </div>
</div>
</body>
</html>

resources/views/win/edit.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 style="text-align: center;color: darkblue">Winner Edit Form</h3></div>


                    <div class="panel-body">
                        <form class="form-horizontal" method="POST" action="{{ route('win.update',$win->id) }}" enctype="multipart/form-data">
                            {{ csrf_field() }}
                            {{ method_field('PATCH') }}
                            <div class="form-group">
                                <label for="title" class="col-md-4 control-label">Title</label>

                                <div class="col-md-6">
                                    <input id="title" type="text" class="form-control" name="title" value="{{ $win->title}}">
                                </div>
                            </div>
                             <div class="form-group">
                                <label for="win_ids" class="col-md-4 control-label">Win Ids</label>

                                <div class="col-md-6">
                                    <input id="win_ids" type="text" class="form-control" name="win_ids" value="{{ $win->win_ids}}" >
                                </div>
                            </div>


                            <div class="form-group">
                                <div class="col-md-6 col-md-offset-4">

                                    <button type="submit" class="btn btn-primary">Submit</button>

                                    <a href="{{ route('win.create') }}" class=" btn btn-primary">Create</a>
                                    <a href="{{ route('win.index') }}" class=" btn btn-primary">win</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/win/index.blade.php
@extends('layouts.master')

@section('content')

 <div class="panel panel-success">

    <div class="panel-heading">
        <h2 style="text-align: center">
            Lists of All Lotteries
            <a href="{{ route('win.create') }}" class=" btn btn-primary pull-right"> <span class=" glyphicon glyphicon-plus-sign"></span>New Lottery Event </a>
        </h2>
        {{--<form class="form-inline" action="{{ route('win.index') }}" method="get">--}}
            {{--<input type="search" class="form-control colorize-theme6-bg" id="search"--}}
                   {{--placeholder="Search . . . ." name="search"--}}
                   {{--value="{{ (isset($_GET['search']) && !empty($_GET['search']))?$_GET['search']:"" }}">--}}
            {{--<button type="submit" class="btn btn-primary">Search</button>--}}
        {{--</form>--}}
        {{--//We Have Total {{$count}} Entries--}}
        <div style="background:#00b38f; color: #ffffff; width: 600px;text-align: center; font-size: 20px;">
            {{ session('message') }}
        </div>
    </div>
     <div class="panel-body">
        <table id="example1" class="table table-responsive table-bordered table-striped">
            <thead >
                <tr class="bg-primary">
                    <th width="100">SL#</th>
                    <th class="text-left">Title</th>
                    <th class="text-right">Action</th>

                </tr>
            </thead>
            <tbody>
                @foreach($wins as $win)

                    <tr>
                        <td>{{ $loop->index + 1}}</td>
                        <td>{{ $win->title}}</td>
                        <td  class="text-right" width="150">
                            <a href="{{ route('win.show',$win->id) }}" class=" btn btn-info" title="View Winners"><span class="glyphicon glyphicon-eye-open"></span></a>
                            <a href="{{ url('winpdf/'.$win->id)}}" class=" btn btn-primary" title="Download PDF "><span class="glyphicon glyphicon-download"></span></a>
                            {{--<a href="#" class=" btn btn-danger" title="Send Mail"><span class="glyphicon glyphicon-envelope"></span></a>--}}
                        </td>
                    </tr>
                @endforeach
            </tbody>

        </table>

        <div class="pull-right">{{ $wins->links() }}</div>
     </div>
</div>
@endsection

resources/views/win/show.blade.php
@extends('layouts.master')

@section('content')

<div class="panel panel-success">

   <div class="panel-heading ">
         <h2>Winners of {{ $win->title }}
         <a href="{{ route('winners.download_excel', $win->id) }}" class=" btn btn-info pull-right">Download Excel</a>&nbsp;
         <a href="{{ route('winners.send_email', $win->id) }}" class=" btn btn-danger pull-right">Send Email</a>&nbsp;
         <a href="{{ route('win.create') }}" class=" btn btn-primary pull-right">Run New Lottery</a>&nbsp;
         <a href="{{ route('win.index') }}" class=" btn btn-primary pull-right">List</a>&nbsp;
       </h2>
       <div style="background:#00b38f; color: #ffffff; width: 600px;text-align: center; font-size: 20px;">
           {{ session('message') }}
       </div>
   </div>
    <div class="panel-body">
     <table class="table table-bordered table-striped">
         <thead >
         <tr class="bg-info">
             <th width="100">SL#</th>
             <th>Name</th>
             <th>Gender</th>
             <th>Ward</th>
             <th>Phone</th>
             <th>Address</th>
         </tr>
         </thead>
         <tbody>
            @foreach( $persons  as $person )
             <tr>
                 <td>{{ $loop->index + 1}}</td>
                 <td>{{ $person->name }}</td>
                 <td>{{ $person->gender }}</td>
                 <td>{{ $person->ward->ward_name }}</td>
                 <td>{{ $person->phone }}</td>
                 <td>{{ $person->address }}</td>
             </tr>
            @endforeach
         </tbody>
     </table>
    </div>
</div>
@endsection